development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: groups
  pool: 5
  username: root
  password:
  #socket: /opt/boxen/data/mysql/socket

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_groups
  pool: 5
  username: root
  password:
  #socket: /opt/boxen/data/mysql/socket

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: groups
  pool: 5
  username: root
  password:
  #socket: /opt/boxen/data/mysql/socket
